name: Sync Leetcode

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Sync
        uses: yijiunchin/leetcode-sync@v1.8
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CN_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_CN_SESSION }}
          destination-folder: "cn-problems"
          verbose: true
          commit-header: "feat: LeetCode CN Sync"
          leetcode-region: "cn"
